import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { api } from '../api';
import { User as UserType } from '../types';

interface LoginProps { onLogin: (user: UserType) => void; }
type View = 'login' | 'recover' | 'success';

const LoginField: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-700">{label}</span><div className="flex h-11 items-center rounded-lg border border-slate-200 bg-white px-3 transition focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-100">{children}</div></label>;

const Login: React.FC<LoginProps> = ({ onLogin }) => {
  const [view, setView] = useState<View>('login');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [email, setEmail] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [remember, setRemember] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => { const saved = localStorage.getItem('mfc_username'); if (saved) { setUsername(saved); setRemember(true); } }, []);
  const login = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { if (remember) localStorage.setItem('mfc_username', username); else localStorage.removeItem('mfc_username'); const result = await api.login(username, password); onLogin(result.user); } catch (err: any) { setError(err.message || 'Não foi possível entrar. Confira o usuário e a senha.'); } finally { setLoading(false); } };
  const recover = (event: React.FormEvent) => { event.preventDefault(); setLoading(true); window.setTimeout(() => { setLoading(false); setView('success'); }, 600); };
  return <main className="grid min-h-[100dvh] place-items-center bg-slate-50 px-4 py-8"><div className="w-full max-w-[390px]"><a href="/site/" className="mb-7 flex flex-col items-center text-center"><span className="grid h-24 w-24 place-items-center rounded-2xl border border-slate-200 bg-white p-2.5 shadow-sm"><img src="/imgs/mfc_logo01.png" className="h-full w-full object-contain" alt="Movimento Familiar Cristão" /></span><b className="mt-3 text-xl font-bold tracking-tight text-slate-900">MFC Gestão</b><span className="mt-1 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-400">Movimento Familiar Cristão</span></a><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7">
    {view === 'login' && <><header className="mb-6 text-center"><h1 className="text-xl font-bold tracking-tight text-slate-900">Área do MFCista</h1><p className="mt-1.5 text-sm text-slate-500">Entre com seus dados para acessar o sistema.</p></header><form onSubmit={login} className="space-y-4"><LoginField label="Usuário"><UserRound size={17} className="mr-2.5 text-slate-400" /><input autoFocus required value={username} onChange={event => setUsername(event.target.value)} className="h-full min-w-0 flex-1 bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400" placeholder="Digite seu usuário" /></LoginField><LoginField label="Senha"><LockKeyhole size={17} className="mr-2.5 text-slate-400" /><input required type={showPassword ? 'text' : 'password'} value={password} onChange={event => setPassword(event.target.value)} className="h-full min-w-0 flex-1 bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400" placeholder="Digite sua senha" /><button type="button" aria-label={showPassword ? 'Ocultar senha' : 'Mostrar senha'} onClick={() => setShowPassword(value => !value)} className="ml-2 text-slate-400 hover:text-blue-600">{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></LoginField><div className="flex items-center justify-between pt-0.5"><label className="flex cursor-pointer items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)} className="h-3.5 w-3.5 rounded border-slate-300 text-blue-600 focus:ring-blue-500" /> Lembrar usuário</label><button type="button" onClick={() => setView('recover')} className="text-xs font-medium text-blue-600 hover:underline">Esqueci minha senha</button></div>{error && <p role="alert" className="rounded-lg border border-rose-100 bg-rose-50 px-3 py-2.5 text-xs font-medium text-rose-700">{error}</p>}<button disabled={loading} className="mt-2 h-11 w-full rounded-lg bg-blue-600 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:opacity-70">{loading ? 'Entrando…' : 'Entrar'}</button></form></>}
    {view === 'recover' && <form onSubmit={recover}><button type="button" onClick={() => setView('login')} className="mb-5 inline-flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-blue-600"><ArrowLeft size={14} /> Voltar</button><header className="mb-6"><h1 className="text-xl font-bold tracking-tight text-slate-900">Recuperar acesso</h1><p className="mt-1.5 text-sm leading-5 text-slate-500">Informe seu e-mail cadastrado para receber as instruções.</p></header><LoginField label="E-mail"><Mail size={17} className="mr-2.5 text-slate-400" /><input autoFocus required type="email" value={email} onChange={event => setEmail(event.target.value)} className="h-full min-w-0 flex-1 bg-transparent text-sm text-slate-800 outline-none" placeholder="voce@exemplo.com" /></LoginField><button disabled={loading} className="mt-5 h-11 w-full rounded-lg bg-blue-600 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:opacity-70">{loading ? 'Enviando…' : 'Enviar instruções'}</button></form>}
    {view === 'success' && <div className="py-4 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 size={29} /></span><h1 className="mt-5 text-xl font-bold tracking-tight text-slate-900">Confira seu e-mail</h1><p className="mt-2 text-sm leading-5 text-slate-500">Se o endereço estiver cadastrado, você receberá as instruções de recuperação.</p><button onClick={() => setView('login')} className="mt-6 text-sm font-medium text-blue-600 hover:underline">Voltar ao login</button></div>}
  </section><div className="mt-5 flex items-center justify-center gap-2 text-[11px] text-slate-400"><span>MFC Gestão</span><span className="h-1 w-1 rounded-full bg-slate-300" /><a href="/site/" className="font-medium text-slate-500 hover:text-blue-600">Site público</a></div></div></main>;
};
export default Login;
